### ISSUE TITLE
Unable to get property 'getPixelLength' of undefined or null reference

### ISSUE THREAD

**Issue by ivleth** [bbecquet/Leaflet.PolylineDecorator#63]
Hi, using leaflet 1.1.0 with your example below gives: 

Unable to get property 'getPixelLength' of undefined or null reference

 // --- Example with an array of Polylines ---
    var multiCoords1 = [
        [[47.5468, -0.7910], [48.8068, -0.1318], [49.1242, 1.6699], [49.4966, 3.2958], [51.4266, 2.8564], [51.7542, 2.1093]],
        [[48.0193, -2.8125], [46.3165, -2.8564], [44.9336, -1.0107], [44.5278, 1.5820], [44.8714, 3.7353], [45.8287, 5.1855], [48.1953, 5.1416]],
        [[45.9205, 0.4394], [46.7699, 0.9228], [47.6061, 2.5488], [47.7540, 3.3837]]
    ];
    var plArray = [];
    for(var i=0; i<multiCoords1.length; i++) {
        plArray.push(L.polyline(multiCoords1[i]).addTo(map));
    }
    L.polylineDecorator(multiCoords1, {
        patterns: [
            {offset: 25, repeat: 50, symbol: L.Symbol.arrowHead({pixelSize: 15, pathOptions: {fillOpacity: 1, weight: 0}})}
        ]
    }).addTo(map);

**Comment by bbecquet** [comment]
Hi! Thanks for reporting.
I attached one of my classes to an existing Leaflet class, which doesn't work anymore with the new version based on ES6 modules. I should refactor everything anyways to follow a cleaner module structure, but in the meantime I fixed this immediate bug in the 1.2.0 version.
Can you confirm it works for you now, and close this issue if it's ok?

**Comment by ivleth** [comment]
Hi, thank you for the quick follow up! I can see your example page is working now with leaflet 1.1.0, so that indicates the issue is solved. Somehow it isn't solved in my project, but I will work on that. Do I understand it correctly that I just overwrite the leaflet.polylineDecorator.js from the dist folder and that's it? Thanks

**Comment by bbecquet** [comment]
That's it, should be alright with the new version of the file from the `dist` folder. If you still encounter problems, check first that's it not related to a previous cached version, and don't hesitate to continue on this issue if it's not really fixed :) I may have overlooked something that didn't appear in the example file only.

**Comment by ivleth** [comment]
thanks, will do!

**Comment by bbecquet** [comment]
I'm sorry, I completely missed that you answered me right after my last message :/
I spent some time today refactoring a lot of things in the project architecture and code. I don't know if you still experienced this issue, but you shouldn't at all with the last version (https://github.com/bbecquet/Leaflet.PolylineDecorator/releases/tag/v1.3.0)

**Comment by ivleth** [comment]
Hi, I reverted everything as I got too many problems, not only on your plug-in but also on others. I will give it a try once I have time again. Thanks

**Comment by hjoertel** [comment]
I tried to use 1.3 as well, downloaded lib/utils.js  lib/L.Symbol.js  lib/L.PolylineDecorator.js
and it did not work. Of course, I changed 
<script src="lib/leaflet.polylineDecorator.js"></script>
to: <script src="lib/L.PolylineDecorator.js"></script>

My code is nearly unchanged:
`var decorator = L.polylineDecorator(polyline, {
		    patterns: [
			// defines a pattern of 10px-wide arrows, repeated every 100px on the line
			{offset: 0, repeat: 100, symbol:
			    L.Symbol.ArrowHead({pixelSize: 15})}
		    ]
		}).addTo(map);
`

Must be a minor thing I'm missing.
Heinz

**Comment by bbecquet** [comment]
Hi!
Actually there is no `lib` directory, this is `src`, and you have to use the script in `dist` instead.
The files in `src` are the dev files, how I split the code, but the ready-to-use version is packaged in a single file in `dist/leaflet.polylineDecorator.js`. If you just link `src/L.PolylineDecorator.js` in your code, it won't be able to import its dependencies. Actually now that I use ES6 syntax it won't even be parsed correctly by the browser.

So yeah, just download and use `dist/leaflet.polylineDecorator.js` and it should work.

**Comment by hjoertel** [comment]
Sorry, 
> Actually there is no lib directory, this is src

lib is my local directory where I do store the js files.
> and you have to use the script in dist instead.

I did and now it works.
But unfortunately, I can not move or drag the map anymore
And after the first klick on one place, the blue arrows are somewhere and not at the red lines
http://www.oertel-halle.de/katrin/index.html

Thanks for your help

**Comment by bbecquet** [comment]
@hjoertel 
I know why it crashes by looking at your page source. You're still using an old version of Leaflet which isn't compatible with my plugin current version, as is written in the readme. Some Leaflet APIs changed between v0.7 and v1, which makes the plugin break, resulting in bugs and loss of interaction after the first refresh occuring on view change.

If you absolutely want to keep using Leaflet v0.7 for your project, I kept the older branch that I don't maintain anymore for this kind of case: `[leaflet-0.7.2](https://github.com/bbecquet/Leaflet.PolylineDecorator/tree/leaflet-0.7.2)`. You could try using the files from it.

But you should definitely use Leaflet 1 instead.

[BTW, I just noticed you weren't the original bug opener, at first I thought I was answering to the same thread of bugs but actually this is completely unrelated. Please open a new issue next time.

And sorry @ivleth for this noise :)]
